package edu.brandeis.cs12b.pa04.provided;


public class VehicleError {
	public static String CAR_MOVE_ERROR = "ERROR: CAR FAILED TO MOVE";
	public static String SNOWPLOW_MOVE_ERROR = "ERROR: SNOWPLOW FAILED TO MOVE";
	public static String LEFTSNOWPLOW_MOVE_ERROR = "ERROR: LEFTSNOWPLOW FAILED TO MOVE";
	public static String RIGHTSNOWPLOW_MOVE_ERROR = "ERROR: RIGHTSNOWPLOW FAILED TO MOVE";
	
	public static String CAR_PLACEMENT_ERROR = "ERROR: CAR FAILED TO BE PLACED";
	public static String SNOWPLOW_PLACEMENT_ERROR = "ERROR: SNOWPLOW FAILED TO BE PLACED";
	public static String LEFTSNOWPLOW_PLACEMENT_ERROR = "ERROR: LEFTSNOWPLOW FAILED TO BE PLACED";
	public static String RIGHTSNOWPLOW_PLACEMENT_ERROR = "ERROR: RIGHTSNOWPLOW FAILED TO BE PLACED";

}